version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '6543:6543'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=9mRE